# Generated by Django 5.2.8 on 2025-11-30 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='odd_empate',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Odd para empate', max_digits=5),
        ),
        migrations.AddField(
            model_name='jogo',
            name='odd_placar_exato',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Odd para placar exato', max_digits=5),
        ),
        migrations.AddField(
            model_name='jogo',
            name='odd_time1',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Odd para vitória do Time 1', max_digits=5),
        ),
        migrations.AddField(
            model_name='jogo',
            name='odd_time2',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Odd para vitória do Time 2', max_digits=5),
        ),
        migrations.AddField(
            model_name='perfil',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1X2', 'Resultado 1X2'), ('PLACAR', 'Placar Exato'), ('VENCEDOR', 'Vencedor')], default='PLACAR', max_length=20)),
                ('aposta_1x2', models.CharField(blank=True, help_text='1, X ou 2', max_length=1, null=True)),
                ('palpite_time1', models.IntegerField(blank=True, null=True)),
                ('palpite_time2', models.IntegerField(blank=True, null=True)),
                ('valor_apostado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odd_aposta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ganho_potencial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('GANHOU', 'Ganhou'), ('PERDEU', 'Perdeu'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10)),
                ('ganho_realizado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostas', to='bets.jogo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
