# Generated by Django 5.2.8 on 2025-11-30 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_jogo_odd_empate_jogo_odd_placar_exato_jogo_odd_time1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='saldo',
        ),
    ]
